Move authorization check until after client request has been fully read.
This was a particularly gnarly issue found when we enabled HTTP
authentication that resulted in requests above a certain size hitting
this error:

urllib2.URLError: <urlopen error [Errno 104] Connection reset by peer>

urllib2.urlopen will first try to connect without credentials.
When the server responds with 401 Unauthorized, it retries with credentials.

RFC 2616 requires the server to fully read the client request before sending
the 401 response. However, our custom CherryPy authentication handler was
running at "on_start_resource", which is before the request has finished
being read. CherryPy would send the 401 and immediately close the client
connection, leading to a client write failure and the above URLError.

Smaller requests could be sent in a single TCP packet (64KB) and thus did not
encounter this issue. Other HTTP clients such as curl avoid this by using the
"Expect: 100-Continue" header when connecting, which avoids sending the
request body until after the server validates headers.

The fix, as is often the case, is a trivial amount of code. Simply move
the authorize check later in request processing to "before_handler".